default: &default
  adapter: postgres
  encoding: utf8
  username: ang
  password: ehr

development:
  database: healthub_development
  <<: *default

test:
  database: healthub_test
  <<: *default

production:
  database: healthub_production
  <<: *default
