development:
  adapter: postgres
  encoding: utf8
  username: ang
  password: ehr
  host: localhost
  database: healthub_development

test:
  adapter: postgres
  encoding: utf8
  username: ang
  password: ehr
  host: localhost
  database: healthub_test

production: 
  database: healthub_production
  adapter: postgres
  encoding: utf8
  username: ang
  password: ehr
  host: localhost