development:
  database: healthub_development
  adapter: postgres
  encoding: unicode
  username: ang
  password: ehr
  host: localhost

test:
  database: healthub_test
  adapter: postgres
  encoding: unicode
  username: ang
  password: ehr
  host: localhost

production: 
  database: healthub_production
  adapter: postgres
  encoding: unicode
  username: ang
  password: ehr
  host: localhost